# Generated by Django 3.2.2 on 2021-06-17 13:05

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=1, upload_to=books.models.poster_path, verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
